# CAHA instrument definitions for filabres

default:
  keywords:
    - NAXIS      # number of data axes
    - NAXIS1     # length of data axis 1
    - NAXIS2     # length of data axis 2
    - OBJECT     # Target description
    - RA         # DD.ddddd [deg]
    - DEC        # +/-DD.ddddd [deg]
    - EQUINOX    # Equinox in years
    - DATE       # file creation date (YYYY-MM-DDThh:mm:ss UT)
    - MJD-OBS    # modified jul. date
    - EXPTIME    # Total integration time (sec)
    - INSTRUME   # instrument ID
    - CCDNAME    # Detector used
    - ORIGSECX   # original size full frame nx
    - ORIGSECY   # original size full frame ny
    - CCDSEC     # orientation to full frame [x1,y1:x2:y2]
    - BIASSEC    # overscan portion of frame [x1:y1,x2:y2]
    - DATASEC    # image portion of frame [x1,y1:x2,y2]
    - CCDBINX    # Binning factor along X
    - CCDBINY    # Binning factor along Y

cafos-imaging:
  name: 'CAFOS'
  obsmode: 'imaging'
  keywords:
    - IMAGETYP   # Type of observation
    - INSFLID    # filter no.
    - INSFLNAM   # filter name
    - INSGRID    # grism no.
    - INSGRNAM   # grism name
  imagetypes:
    bias:
      signature:
        - DATASEC
    flat:
      signature:
        - DATASEC
        - DATASEC
        - INSGRID
        - INSFLID
    science:
      signature:
        - DATASEC
