# CAHA instrument definitions for filabres

default:
  keywords:
    - NAXIS1
    - NAXIS2
    - OBJECT
    - RA
    - DEC
    - EQUINOX
    - DATE
    - EXPTIME
    - INSTRUME
    - CCDNAME
    - CCDSEC
    - BIASSEC
    - CCDBINX
    - CCDBINY

cafos-imaging:
  name: 'CAFOS'
  obsmode: 'imaging'
  keywords:
    - IMAGETYP
    - INSFLNAM
  calibrations:
    - bias
    - flat
